name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  backend_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Run backend tests
        working-directory: backend
        run: npm test

      - name: Lint backend code (does not fail pipeline)
        working-directory: backend
        run: npm run lint

  deploy_backend:
    needs: [backend_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy backend to Render
        if: ${{ github.event_name == 'push' }}
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_BACKEND_API_KEY }}
        run: |
          curl -X GET "https://api.render.com/deploy/srv-${{ secrets.RENDER_BACKEND_SERVICE_ID }}?key=${{ secrets.RENDER_BACKEND_API_KEY }}"

  frontend_pipeline:
    needs: [deploy_backend]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run frontend tests
        working-directory: frontend
        run: npm test

      - name: Lint frontend code (does not fail pipeline)
        working-directory: frontend
        run: npm run lint

  deploy_frontend:
    needs: [frontend_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy frontend to Render
        if: ${{ github.event_name == 'push' }}
        env:
          RENDER_FRONTEND_SERVICE_ID: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_FRONTEND_API_KEY }}
        run: |
          curl -X GET "https://api.render.com/deploy/srv-${{ secrets.RENDER_FRONTEND_SERVICE_ID }}?key=${{ secrets.RENDER_FRONTEND_API_KEY }}"

  tag_release:
    needs: [deploy_frontend]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
